[opener]
edit = [
    { run = 'helix "$@"', block = true, for = "unix" },
    { run = 'helix %*', block = true, for = "windows" },
]

[[opener.bulk-rename]]
run   = 'helix "$@"'
block = true

[[open.prepend_rules]]
name = "bulk-rename.txt"
use  = "bulk-rename"
